### ISSUE TITLE
[page-management]: editing of page slack integraton doesnt work [every run]

### ISSUE THREAD

**Issue by kristapscerminieks** [foo-software/status#1]
**PRE-CONDITIONS:**
1. Page for lighthouse is configured;
2. Slack integration is configured (foo account linked to slack channel);
3. Page is linked to configured slack integration.

**STEPS:**
1. User navigates to advanced page management (pages -> update -> advanced);
2. User checks "Every run" toggle and saves changes;
3. User refereshes page and observes

**ACTUAL RESULT:**
1. "Every run" checkbox is still unchecked

**EXPECTED RESULT:**
1. "Every run" checkbox is checked (enabled)

**COMMENTS:**
1. I checked `pageUpdate` mutation , there I can see that it's sent as `null`, it seems like the value is not taken from the checkbox and is hardcoded to whatever the server responds with beforehand.

```
 "mobileAlerts": [
    {
      "all": null,
      "id": "668d3b88cb89....."
    }
  ],
```

**Comment by adamhenson** [comment]
Thanks for providing the steps. I think step 2 needs to be different. You should check the checkbox first, then select the channel from the "Add Slack Alerting" button dropdown, then click save. See [article here](https://www.foo.software/posts/how-to-configure-slack-notifications-with-lighthouse-monitoring#adding-slack-connections-to-pages-for-lighthouse-monitoring-notifications) and screen recording below.

https://github.com/user-attachments/assets/4c0f5ebe-3f86-4e11-b30a-3f17376e91ce

**Comment by kristapscerminieks** [comment]
Hey, thanks @adamhenson for the response. Unfortunately, this is not the case, I already have selected Slack channel. In the below video I am doing what you suggest, but it doesn't work, even if I re-connect the Slack reporting:


https://github.com/user-attachments/assets/45ec495b-4cbf-4c9d-a0ce-860da8482d3a

**Comment by adamhenson** [comment]
You can’t update the channel setting after. Simply remove the channel by clicking the “x” on the badge and re-add it. But make sure to check the box before re-adding.

**Comment by kristapscerminieks** [comment]
@adamhenson Thanks, tried it that way and it worked (I can see that in the request "all" is set to `true`), although UI does not show that (after the page reload). 


Then I guess there is another issue... We had slack integration set up, we are running lighthouse every morning and results were sent to slack, everything worked fine. But then we stopped receiving notifications, I did test the slack integration (with the test button) and it works fine, but notifications about runs are still not being sent, I tried triggering run by hand and automatically. 

I thought maybe it was because we didn't have checked "Every run" in the page management, but as it turns out it is selected, we just don't see that in UI. Do you have any idea what might be wrong or how to debug/ fix it? 

Based on the response from `page` query the configuration is there
```
 "desktopAlerts": [
              {
                "all": true,
                "id": "66b067dba4dc6e0032f958ac",
                "__typename": "PageSlackAlertConnection"
              }
            ],

 "mobileAlerts": [
              {
                "all": true,
                "id": "66b067dba4dc6e0032f958ac",
                "__typename": "PageSlackAlertConnection"
              }
            ],

```

Thank you in advance!

**Comment by adamhenson** [comment]
Hi @kristapscerminieks - thanks for the info and your patience. I can understand how this part of the UI could be confusing. The "Every run" checkbox doesn't reflect the existing page alerts, but only used for adding new alerts. The icon as shown in the screenshot is what represents if a channel is attached to the page with every run or not (the infinity icon means every run).

I checked your account and can confirm the pages now have a Slack channel attached for every run. If you continue to have issues, please email us at hello@foo.software and list out any times you were expecting to receive Slack notifications, but didn't (also let us know the time zone).

<img width="480" alt="Screenshot 2024-08-05 at 9 49 19 AM" src="https://github.com/user-attachments/assets/576c4eb7-0595-4b1f-a72f-ce9394499d01">

**Comment by kristapscerminieks** [comment]
Thanks, now I understand, I had no idea that that icon meant anything. Will reach out to support email 👍
